# NUMPY INDEXING AND SLICING OF VECTIOR

In [1]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[6]

np.int64(17)

In [6]:
arr[9]

np.int64(20)

In [10]:
#slicing
arr[:5]


array([11, 12, 13, 14, 15])

In [11]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr[3:6]

array([14, 15, 16])

In [13]:
arr[3::2]

array([14, 16, 18, 20])

# NUMPY INDEXING AND SLICING OF MATRIX

In [15]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr[5] # for row

array([26, 27, 28, 29, 30])

In [17]:
arr[0,0] # for single element

np.int64(1)

In [18]:
arr[0,4]

np.int64(5)

In [20]:
slice = arr[0:2,1:3]

In [21]:
slice

array([[2, 3],
       [7, 8]])

In [22]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [23]:
# for columns
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

# BOOLEAN INDEXING

In [25]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
bool_index = arr %2 == 0

In [27]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [31]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])