# Aarray Opration

In [2]:
import numpy as np

In [2]:
# 1. Arithmetic opration
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [6]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [7]:
arr = a1+a2

In [8]:
a1-a2

array([-5, -5, -5, -5, -5])

In [9]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [10]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1 // a2


array([0, 0, 0, 0, 0])

In [12]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# Broadcasting

In [19]:
l = [10,20,30,40,50]
arr = np.array(l)

In [20]:
arr + 10

array([20, 30, 40, 50, 60])

In [18]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# Deep and Shallow copy

In [22]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
slice =a[:5]
slice  = slice*10
slice

array([10, 20, 30, 40, 50])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
a [4:6] *10

array([50, 60])

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a  # take a diffrent location
b = a

In [30]:
b[0] = 99

In [31]:
b # deep copy 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
# shallow copy

a 
b = a.copy


In [ ]:
b[0] = 34
b

In [38]:
a

array([36,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Matrix opration

In [41]:
a = np.array([[1,2,],[3,4]]) 
b = np.array([[5,6,],[7,8]]) 

In [42]:
a


array([[1, 2],
       [3, 4]])

In [43]:
b

array([[5, 6],
       [7, 8]])

In [45]:
a @ b

array([[19, 22],
       [43, 50]])

In [46]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

# Advance array manipaltion

 #### stacking array

In [3]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [4]:
np.vstack((a,b))  # v- vertical 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
np.hstack((a,a))   #  h - horizental

array([1, 2, 3, 4, 1, 2, 3, 4])

In [7]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting Array

In [9]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [11]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]