In [1]:
import numpy as np

# Basic Array creation

In [2]:
arr = np.array([1,2,3,4,])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
# python list 
a = [1,2,4,4.5]
a

[1, 2, 4, 4.5]

In [6]:
# convert python list  into numpy arr 

np.array(a)

array([1. , 2. , 4. , 4.5])

In [7]:
 # single dimendional 
l  = [[1,2,4],[5,3,6],[7,8,9]]
l

[[1, 2, 4], [5, 3, 6], [7, 8, 9]]

In [8]:
# 1 D to 2 D 
np.array(l)

array([[1, 2, 4],
       [5, 3, 6],
       [7, 8, 9]])

In [9]:
# range 
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.zeros((4,4))

In [11]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:

arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#linspace 
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Randam generation function 



In [14]:
np.random.rand(10)  # 0 to 1

array([0.58226879, 0.69642193, 0.92169259, 0.25937208, 0.21929   ,
       0.44879484, 0.51678913, 0.41209672, 0.69769756, 0.57673489])

In [15]:
np.random.randn(10) # 3 to -3

array([ 1.19754622, -0.94943376,  2.13444238,  0.41978262,  0.38162331,
        0.19691375,  0.45056685, -0.61331034,  0.28168285,  0.76221969])

In [16]:
np.random.randint(10,20,10)

array([17, 10, 16, 14, 13, 15, 12, 17, 15, 19], dtype=int32)

# Array attributes

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int64')

# Array Method

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [25]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [26]:
arr.mean()

np.float64(5.0)

In [27]:
arr.std()

np.float64(2.581988897471611)

In [28]:
arr.argmax()

np.int64(8)

In [29]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [41]:
arr = np.arange(1,31)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [42]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])