In [ ]:
import numpy as np
arr = np.array([1,2,3])

In [ ]:
arr

array([1, 2, 3])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((4,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [ ]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
arr = np.array([[1,2,3],[5,6,7],[12,13,14]])

In [ ]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [12, 13, 14]])

In [ ]:
arr.shape

(3, 3)