In [1]:
import numpy as np

# Valid soddoku

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
s.sum()

np.int64(405)

In [4]:
b = np.sum(s,axis = 1)
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [5]:
b = np.sum(s,axis = 1)
for i in b:
    if i !=45:
        print("sodoku is not valid")
        break
    else:
        print("For row is valid ")

For row is valid 
For row is valid 
For row is valid 
For row is valid 
For row is valid 
For row is valid 
For row is valid 
For row is valid 
For row is valid 


In [6]:
c = np.sum(s,axis = 1)
for i in b:
    if i !=45:
        print("sodoku is not valid")
        break
    else:
        print("For colum is valid ")

For colum is valid 
For colum is valid 
For colum is valid 
For colum is valid 
For colum is valid 
For colum is valid 
For colum is valid 
For colum is valid 
For colum is valid 


In [7]:
# sliceing

In [8]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [9]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [10]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [14]:
s[3:6,3:6]

array([[7, 6, 1],
       [8, 5, 3],
       [9, 2, 4]])

In [15]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [17]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = (s[i:i+3,j:j+3])
        print(n.sum())

45
45
45
45
45
45
45
45
45


 # general questuin

In [87]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [45]:
# Get the shape of the matrix
data.shape

(5, 3)

In [46]:
# find the average  age sum of the matrix
np.mean(data[:,0])

np.float64(18.4)

In [47]:
# Extract math markes of all student 
data[:,1]

array([85, 92, 76, 65, 90])

In [48]:
# find the highest science marks
np.max(data[:,2])

np.int64(95)

In [50]:
# Get details of the student who scored more then 90 in maths 
data[data[:,2] > 90]


array([[17, 76, 95]])

In [59]:
#increase maths marks all of student by 4
data[:,1 ] + 5


array([90, 97, 81, 70, 95])

In [68]:
# find how many student are younger then 19
len(data[ data[:,0] < 19])


3

In [72]:
# calculeter  the average marks in each subject ( colums-wise mean)
np.mean(data[:,1:],axis = 0)

array([81.6, 83.2])

In [74]:
# Get the data of student scored at least 80 in bath subjects
data[(data[:,1]>=80) & (data[:,2] >=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [88]:
# Replace all science marks  < 75 with 0

data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])