# Python zip list


In [15]:
l1 =[2,4,6,8,9]
l2 =[ 1,3,5,7,10]
list(zip(l1,l2))

[(2, 1), (4, 3), (6, 5), (8, 7), (9, 10)]

# Adding to list by using python



In [9]:
# using python list 

import numpy as np
import time

size = 10_00_000
l1 = list(range(size))
l2 = list(range(size))

start = time.time()

add = [x+y for x,y in zip (l1,l2)]
end = time.time()
print(add[0:10])
print(end - start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.19960451126098633


# Using  numpy  array
#####  NumPy stores data in a contiguous memory block, making access faster than lists.🔹 shape shows the dimensions of an array.


In [12]:
import numpy as np
import time

size = 10_00_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()

add = l1+l2
end = time.time()
print(add[0:10])

print(end - start)


[ 0  2  4  6  8 10 12 14 16 18]
0.006932258605957031


# 2D array in numpy

In [19]:
np.array([[1,2,3,4,],[5,6,7,8,]]) 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
np.array([[1,2,3,4,],[5,6,7,8,1]]) 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# Importants
This error occurs because you're trying to create a NumPy array with rows of different lengths, which NumPy doesn't allow. The first row has 4 elements `[1,2,3,4]`, but the second row has 5 elements `[5,6,7,8,9]`.

NumPy arrays must be rectangular, meaning all rows must have the same number of elements.


In [20]:
# type cheak 
arr = np.array([[1,2,3,4,],[5,6,7,8,]]) 
type(arr)

numpy.ndarray

In [21]:
arr.shape

(2, 4)

# Numpy  efficiency 

In [29]:
# NumPy arrays use significantly less memory compared to Python lists


In [28]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)

print("python list size " , sys.getsizeof(list_data)*len(list_data),"bytes")
print("numpy array size " , numpy_data.nbytes , "bytes")

python list size  8056000 bytes
numpy array size  8000 bytes


# numpy vectorization - No more loop
#### NumPy avoids loops by applying operations to entire arrays at once using SIMD
#### (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a
#### CPU-level optimization provided by modern processors.

In [33]:
# python list loop
list1=[2,3,5,6,7]

list_square = [x**2 for x in list1]
print(list_square)


# numpy (vectorization)
arr1=np.array([2,5,6,7,3])
numpy_square = arr1**2
print(numpy_square)

[4, 9, 25, 36, 49]
[ 4 25 36 49  9]


In [45]:
import numpy as np 
import time 

# Python list
list1=[2,3,5,6,7]
start = time.time()
add_list_square = [x**2 for x in list1]
end = time.time()
print(list_square , start - end)

# Numpy arry

arr1= np.array([2,3,5,6,7])
start = time.time()
numpy_square = arr1**2
end = time.time()
print(numpy_square ,  start- end)

[4, 9, 25, 36, 49] -0.00010728836059570312
[ 4  9 25 36 49] -0.0001227855682373047
